version: '3.9'

services:
  tg_bot_db:
    container_name: tg_bot_db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
      DATABASE_HOST: ${PG_HOST}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
  tg_bot:
    container_name: tg-bot
    build: .
    ports:
      - "8080:8080"
    depends_on:
      tg_bot_db:
        condition: service_healthy
    restart: unless-stopped

volumes:  
  postgres-data:
